#Mysql
#spring.datasource.url=jdbc:mysql://localhost:3306/book_ex?useUnicode=true&charaterEncoding=utf-8
spring:
  datasource:
    url: jdbc:mysql://tripper.cg08tx0ixoqm.ap-northeast-2.rds.amazonaws.com/book_ex?useUnicode=true&charaterEncoding=utf-8
    username: tripper
    password: somatripper
    driverClassName: com.mysql.jdbc.Driver
#Jpa Option
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: false
    show-sql: true


